release :
	cp DOCUMENTATION ../ 
	cp CHANGELOG ../
	cp VERSION ../
	cp apply/* ../apply/ 
	cp cheers.php ../ 
	cp faq.php ../ 
	cp foc/* ../foc/ 
	cp footer.php ../ 
	cp header.php ../ 
	cp imgs/*.flv ../imgs/ 
	cp imgs/*.png ../imgs/
	cp imgs/tie/* ../imgs/tie/
	cp include/* ../include/ 
	cp index.php ../ 
	cp main.php ../ 
	cp pinktie.php ../
	cp retreat.php ../
	cp sidebar.php ../
	cp splash_style.css ../
	cp style.css ../
	cp teams.php ../
	cp suggestionbox.php ../
	cp leader_sizes.php ../
	cp update_profile.php ../
